resource_types:
  - name: helm
    type: docker-image
    source:
      repository: alpine/helm
      tag: "3.5.2"

resources:
  - name: event-stats-chart
    type: git
    source:
      uri: "https://github.com/harshvirani7/event-stats-test.git"
      branch: main

jobs:
  - name: deploy-helm-chart
    plan:
      - get: event-stats-chart
        trigger: true
      - task: deploy-helm
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine/helm
              tag: "3.5.2"
          inputs:
            - name: event-stats-chart
          run:
            path: sh
            args:
              - -exc
              - |
                helm repo add stable https://charts.helm.sh/stable
                helm upgrade --install event-stats-chart event-stats-chart/event-stats-chart-0.1.0.tgz --namespace default
