{
 "title": "Event Stats",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Count of Total Successful API calls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(myapp_vsapi_http_response_time_count{status=~\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of Total Failed API calls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(myapp_vsapi_http_response_time_count{status=~\"400\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Failed API calls",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(myapp_vsapi_http_response_time_count{status=\"400\"}) / sum(myapp_vsapi_http_response_time_count)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (myapp_vsapi_http_response_time_count{status=~\"200\"})",
     "legendFormat": "status='2xx'"
    },
    {
     "expr": "sum by (status) (myapp_vsapi_http_response_time_count{status=~\"400\"}) ",
     "legendFormat": "status='4xx' "
    }
   ]
  },
  {
   "title": "Total Stored Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "myapp_connected_devices", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "4xx Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(myapp_vsapi_http_response_time_count{status=\"400\"}[$__rate_interval])",
     "legendFormat": "{{ path }}, status = {{ status }}"
    }
   ]
  },
  {
   "title": "2xx Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(myapp_vsapi_http_response_time_count{status=\"200\"}[$__rate_interval])",
     "legendFormat": "{{ path }}, status = {{ status }}"
    }
   ]
  },
  {
   "title": "4xx Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(myapp_vsapi_http_response_time_sum{status=\"400\"}[$__interval])) / sum(rate(myapp_vsapi_http_response_time_count{status=\"400\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "2xx Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(myapp_vsapi_http_response_time_sum{status=\"200\"}[$__interval])) / sum(rate(myapp_vsapi_http_response_time_count{status=\"200\"}[$__interval]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "totalCountByEventType Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(myapp_vsapi_http_response_time_bucket{path=\"/eventStats/totalEventCountByEventType/\", status=\"200\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(myapp_vsapi_http_response_time_bucket{path=\"/eventStats/totalEventCountByEventType/\", status=\"200\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(myapp_vsapi_http_response_time_bucket{path=\"/eventStats/totalEventCountByEventType/\", status=\"200\"}[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "totalEventCountByCameraId Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(myapp_vsapi_http_response_time_bucket{path=\"/eventStats/totalEventCountByCameraId/\", status=\"200\"}[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(myapp_vsapi_http_response_time_bucket{path=\"/eventStats/totalEventCountByCameraId/\", status=\"200\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(myapp_vsapi_http_response_time_bucket{path=\"/eventStats/totalEventCountByCameraId/\", status=\"200\"}[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "App Version (Gauge)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_info", "legendFormat": "{{ version }}" }
   ]
  }
 ]
}