apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: {{ .Values.elasticsearch.image }}
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: {{ .Values.elasticsearch.containerPort }}
              name: http
            - containerPort: {{ .Values.elasticsearch.transportPort }}
              name: transport
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: {{ .Values.elasticsearch.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: {{ .Values.elasticsearch.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - port: {{ .Values.elasticsearch.containerPort }}
      targetPort: {{ .Values.elasticsearch.containerPort }}
      name: http
    - port: {{ .Values.elasticsearch.transportPort }}
      targetPort: {{ .Values.elasticsearch.transportPort }}
      name: transport
