apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-kibana
  labels:
    app: kibana
spec:
  replicas: {{ .Values.kibana.replicas }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: {{ .Values.kibana.image }}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.kibana.elasticsearchHost }}
            - name: XPACK_SECURITY_ENABLED
              value: "false"
          ports:
            - containerPort: {{ .Values.kibana.containerPort }}
              name: http
          readinessProbe:
            httpGet:
              path: /app/kibana
              port: {{ .Values.kibana.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /app/kibana
              port: {{ .Values.kibana.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: {{ .Values.kibana.containerPort }}
      targetPort: {{ .Values.kibana.containerPort }}
      name: http
