apiVersion: v1
kind: Service
metadata:
  name: event-stats-test
spec:
  selector:
    app: event-stats-test
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.eventStats.containerPort }}
      targetPort: {{ .Values.eventStats.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis.containerPort }}
      targetPort: {{ .Values.redis.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.prometheus.containerPort }}
      targetPort: {{ .Values.prometheus.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.grafana.containerPort }}
      targetPort: {{ .Values.grafana.containerPort }}
